image: passp-dev-rc1.msk.mts.ru:5005/external-websso/dockers/maven-custom:3-jdk-8

variables:
  GIT_SSL_NO_VERIFY: "1"
  MAVEN_OPTS: ""
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version"

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS -DskipTests clean install
  artifacts:
    paths:
      - "*/target"
      - "*/*/target"

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test
  allow_failure: true

test-sonar:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS -DskipTests install
    - mvn $MAVEN_CLI_OPTS sonar:sonar -Dsonar.host.url=$WEBSSO_SONAR_URL -Dsonar.login=$WEBSSO_SONAR_TOKEN -Dsonar.gitlab.commit_sha=$(git log --pretty=format:%H origin/master..$CI_COMMIT_SHA | tr '\n' ',') -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME -Dsonar.gitlab.project_id=$CI_PROJECT_ID -Dsonar.gitlab.unique_issue_per_inline=true
  allow_failure: true

deploy:
  stage: deploy
  dependencies:
    - build
  script:
    - mvn $MAVEN_CLI_OPTS -DskipTests deploy

